### ISSUE TITLE
🐛 Review if security PRs will break stuff?

### ISSUE THREAD

**Issue by janhalen** [OS2fleetoptimiser/OS2fleetoptimiser#16]
👋🏻 Hi @OS2fleetoptimiser/maintainers !

After setting up dependabot, we have some [auto-generated PRs](https://github.com/OS2fleetoptimiser/OS2fleetoptimiser/pulls/app%2Fdependabot) that needs a bit of review, whether they'll introduce some changes that breaks stuff.

I hope you can find time to discuss a resolution to these soon and get the triaging done as 4 of the alerts that potentially affect the product has a "High" severity.

**Comment by andreasDroid** [comment]
@janhalen , sure. We will check this and resolve asap.
