### ISSUE TITLE
📃PO check new changes

### ISSUE THREAD

**Issue by andreasDroid** [OS2fleetoptimiser/OS2fleetoptimiser#4]
Hi @sobuos 
Can I get you to check the listed features in the test environment, and check them off if it looks good to you. Then I'll make the changes available in production.

https://testing.fleetoptimiser.droidsagencyai.com

**Front page - simulation setup**
- [x] Navigation: Collapse simulation in left-hand navigation 
- [x] Simulation setup: Simulation buttons in the bottom of vehicle selection on the simulation-setup
- [x] Simulation setup: Icons in simulation-setup displaying vehicle type (unknown, fossil, electrical, bike, electrical bike)

**Automatic simulation**
- [x] Rename to automatic simulation
- [x] #5
- [x] Automatic simulation: download results to excel
- [x] Automatic simulation: show count difference in vehicles in results 
- [x] Automatic simulation: tips box (only shows on "bad solutions")
- [x] Automatic simulation: remove input fields (economy, emission) 

**Intelligent allocation**
- [x] Intelligent allocation: renaming the feature
- [x] Intelligent allocation: make more visible in the setup

**Configuraiton**
- [x] Configuration: import meta-data in bulk, checks validty of input
- [x] Configuration: color vehicles based on expiration or lack of meta-data

**Read-write access**
- [x] You have write access on the testing env, I can change this so you can test read access, when you're ready.

For you to be able to run simulations, select start date march 2022 - april 2022.

Br. Andreas

**Comment by sobuos** [comment]
Hi @andreasDroid 
Looks great! I have tested all the functionality and it works as intended. 

A few comments related to ease of use:
- Configuration: Can we add two info-boxes: 1) Import function is only for editing of vehicles. Adding of new test-vehicles must be done by the "add new vehicle" function and 2) what does the colors mean? (not sure that users remember whether it is expiration or lack of meta-data
- Simulations (both manual and automatic): Can you wrap or split up the text in "bicycle properties"? It is not possible to see all the text as it exceeds the buttons width

Br. Sofie

**Comment by andreasDroid** [comment]
- Info added beside import button
- Status added to the row table
- "Cykelegenskaber" fits to button

![billede](https://github.com/user-attachments/assets/e821c22b-3282-4141-baa4-0bbf1ac8ab5b)
![billede](https://github.com/user-attachments/assets/c4e96354-a072-4433-8593-544b8774f84e)

**Comment by janhalen** [comment]
@sobuos: Should we practice the process of signing of on this test and merging the codechanges together tomorrow at the backlog meeting, or should we wait for a seperate session either in person or via video?

**Comment by sobuos** [comment]
@janhalen I have time tomorrow until 10, so let's do it :-)
